In [2]:
import pandas as pd
from nba_api.stats.endpoints import commonplayerinfo

In [5]:
nba_players = pd.read_csv("nba_players")

In [7]:
player_ids = nba_players['PERSON_ID']

In [13]:
player_info = pd.DataFrame()

for player_id in player_ids:
    info = commonplayerinfo.CommonPlayerInfo(player_id=player_id)
    df_info = info.get_data_frames()[0]
    player_info = pd.concat([player_info, df_info], ignore_index=False)

# Display player details
player_info

,PERSON_ID,FIRST_NAME,LAST_NAME,DISPLAY_FIRST_LAST,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FI_LAST,PLAYER_SLUG,BIRTHDATE,SCHOOL,COUNTRY,...,PLAYERCODE,FROM_YEAR,TO_YEAR,DLEAGUE_FLAG,NBA_FLAG,GAMES_PLAYED_FLAG,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,GREATEST_75_FLAG
0,78331,Mychal,Thompson,Mychal Thompson,"Thompson, Mychal",M. Thompson,mychal-thompson,1955-01-30T00:00:00,Minnesota,USA,...,HISTADD_mychal_thompson,1978,1990,N,Y,Y,1978,1,1,N
0,76736,Phil,Ford,Phil Ford,"Ford, Phil",P. Ford,phil-ford,1956-02-09T00:00:00,North Carolina,USA,...,HISTADD_phil_ford,1978,1984,N,Y,Y,1978,1,2,N
0,77984,Rick,Robey,Rick Robey,"Robey, Rick",R. Robey,rick-robey,1956-01-30T00:00:00,Kentucky,USA,...,HISTADD_rick_robey,1978,1985,N,Y,Y,1978,1,3,N
0,77952,Micheal Ray,Richardson,Micheal Ray Richardson,"Richardson, Micheal Ray",M. Richardson,micheal-ray-richardson,1955-04-11T00:00:00,Montana,USA,...,HISTADD_micheal_ray_richardson,1978,1985,N,Y,Y,1978,1,4,N
0,78139,Purvis,Short,Purvis Short,"Short, Purvis",P. Short,purvis-short,1957-07-02T00:00:00,Jackson State,USA,...,HISTADD_purvis_short,1978,1989,N,Y,Y,1978,1,5,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,1626161,Willie,Cauley-Stein,Willie Cauley-Stein,"Cauley-Stein, Willie",W. Cauley-Stein,willie-cauley-stein,1993-08-18T00:00:00,Kentucky,USA,...,willie_cauley-stein,2015,2022,Y,Y,Y,2015,1,6,N
0,1626144,Emmanuel,Mudiay,Emmanuel Mudiay,"Mudiay, Emmanuel",E. Mudiay,emmanuel-mudiay,1996-03-05T00:00:00,Guangdong,Democratic Republic of the Congo,...,emmanuel_mudiay,2015,2021,Y,Y,Y,2015,1,7,N
0,1626169,Stanley,Johnson,Stanley Johnson,"Johnson, Stanley",S. Johnson,stanley-johnson,1996-05-29T00:00:00,Arizona,USA,...,stanley_johnson,2015,2022,Y,Y,Y,2015,1,8,N
0,1626163,Frank,Kaminsky,Frank Kaminsky,"Kaminsky, Frank",F. Kaminsky,frank-kaminsky,1993-04-04T00:00:00,Wisconsin,USA,...,frank_kaminsky,2015,2022,Y,Y,Y,2015,1,9,N
0,1626159,Justise,Winslow,Justise Winslow,"Winslow, Justise",J. Winslow,justise-winslow,1996-03-26T00:00:00,Duke,USA,...,justise_winslow,2015,2022,Y,Y,Y,2015,1,10,N

In [ ]:
player_info.to_csv("player_info.csv", index=False)